### ISSUE TITLE
Tool is not properly working

### ISSUE THREAD

**Issue by dayaramgodara93** [knassar702/scant3r#18]
**Describe the bug**
When ever I am trying to run the tool it is not running giving me some error.

**To Reproduce**
I am attaching the error message below sir.
```
   ____              __  ____
  / __/______ ____  / /_|_  /____
 _\ \/ __/ _ `/ _ \/ __//_ </ __/
/___/\__/\_,_/_//_/\__/____/_/

[!] Coded by: Khaled Nassar @knassar702
[!] Version: 0.7#Beta

Traceback (most recent call last):
  File "/scant3r/./scant3r.py", line 59, in <module>
    M.run(opts,msg)
  File "/scant3r/core/libs/all/module_loader.py", line 35, in run
    res = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/scant3r/modules/finder/__init__.py", line 48, in main
    v = start(opts,r)
  File "/scant3r/modules/finder/__init__.py", line 26, in start
    part = dump_response(r).decode()
  File "/scant3r/core/libs/all/data.py", line 38, in dump_response
    body += str(request.status_code).encode("utf8")
AttributeError: 'int' object has no attribute 'status_code'


**Additional context**
i have tried to reinstall the tool but still facing the same issue sir. Please help me to run the tool.

Thank you so much for this awesome tool  sir.

**Comment by knassar702** [comment]
hey @dayaramgodara93 
thanks for this report , This is because http request error

```bash
knassar702@OurPc ☭: ~/myproject/scant3r $ echo 'http://manasfasf.com/?t=1' | ./scant3r.py -m finder -d -n

HTTPConnectionPool(host='manasfasf.com', port=80): Max retries exceeded with url: /?t=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55c7371f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='manasfasf.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55c73717f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

```

fixed here f8a3a9de97d1b378df21a91d34cb77df7bf7417d
