### ISSUE TITLE
AttributeError: 'list' object has no attribute 'json'

### ISSUE THREAD

**Issue by karim-jpg** [knassar702/scant3r#48]
hello, i'm getting this error

└─# echo 'http://testphp.vulnweb.com/showimage.php' | ./scant3r.py -m lorsrf -x 'http://%PARAM%.xxxxxxxxxx.interact.sh/%PATH%' -M GET 1 ⨯
__ _____
______________ _____ / /|__ /_____
/ / / __ `/ __ / // </ /
( ) // // / / / / // / /
//___/_,// //_/___//

[!] Coded by: Khaled Nassar @knassar702
[!] Version: 0.8#Beta

[INFO][2022-02-03,17:29:25] scant3r -> Run modules.python.lorsrf
[ERROR][2022-02-03,17:29:30] requester -> HTTPSConnectionPool(host='odiss.eu', port=1337): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f34e9ab5ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
File "/home/kalirobot/Tools/scant3r/./scant3r.py", line 70, in
M.run(opts, Http(opts))
File "/home/kalirobot/Tools/scant3r/core/libs/all/module_loader.py", line 103, in run
res = future.result()
File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
return self.__get_result()
File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
raise self._exception
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/kalirobot/Tools/scant3r/modules/python/lorsrf/init.py", line 6, in main
Lorsrf(opts, http).start()
File "/home/kalirobot/Tools/scant3r/modules/python/lorsrf/lorsrf.py", line 30, in init
self.host = self.oob_host.new()
File "/home/kalirobot/Tools/scant3r/core/libs/all/hosts.py", line 25, in new
self.host = req.json()['id'] + '.odiss.eu'
AttributeError: 'list' object has no attribute 'json'

**Comment by karim-jpg** [comment]
hello @knassar702 okay and thank you
