### ISSUE TITLE
[BUG] No output result

### ISSUE THREAD

**Issue by lworld0x00** [knassar702/scant3r#62]
**Describe the bug**
Not sure if i use it in the right way. There is no output result.

**To Reproduce**
* Your command
```
$ echo "http://testphp.vulnweb.com/listproducts.php?cat=1" | scant3r -m all
```

* Copy your logging file (`~/.scant3r.log` by default) make sure to check core/data.py

```code
scant3r     : DEBUG    trying to load scant3r.modules.ssti
scant3r     : DEBUG    LOADED
scant3r     : DEBUG    trying to load scant3r.modules.firebase
scant3r     : DEBUG    LOADED
scant3r     : DEBUG    trying to load scant3r.modules.req_callback
scant3r     : DEBUG    LOADED
scant3r     : DEBUG    trying to load scant3r.modules.xss
scant3r     : ERROR    invalid syntax (payload_gen.py, line 150)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scant3r/core/module_loader.py", line 33, in get
    import_obj = importlib.import_module(import_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/scant3r/modules/xss/__init__.py", line 17, in <module>
    from .payload_gen import XSS_PAYLOADS
  File "/usr/local/lib/python3.6/site-packages/scant3r/modules/xss/payload_gen.py", line 150
    match location:
                 ^
SyntaxError: invalid syntax
scant3r     : DEBUG    Trynig to Start <scant3r.modules.ssti.Main object at 0x7fe51b40bf28>
scant3r     : DEBUG    SSTI: GENERATE A NEW URL: http://testphp.vulnweb.com/listproducts.php?cat=1scanKZWr
scant3r     : DEBUG    STARTED <scant3r.modules.ssti.Main object at 0x7fe51b40bf28>
scant3r     : DEBUG    Trynig to Start <scant3r.modules.req_callback.Main object at 0x7fe51a3db5f8>
scant3r     : DEBUG    STARTED <scant3r.modules.req_callback.Main object at 0x7fe51a3db5f8>
scant3r     : DEBUG    Trynig to Start <scant3r.modules.firebase.Main object at 0x7fe51a3db9b0>
scant3r     : DEBUG    STARTED <scant3r.modules.firebase.Main object at 0x7fe51a3db9b0>
scant3r     : DEBUG    Check for Read permission -> https://vulnweb-dev.firebaseio.com
scant3r     : DEBUG    Check for Write permission -> https://vulnweb-dev.firebaseio.com
scant3r     : DEBUG    REFLECTED KZW on http://testphp.vulnweb.com/listproducts.php?cat=1scanKZWr
scant3r     : DEBUG    SSTI: MATCHING  WITH scan10tr
scant3r     : DEBUG    Check for Read permission -> https://vulnweb.firebaseio.com
scant3r     : DEBUG    Check for Write permission -> https://vulnweb.firebaseio.com
scant3r     : DEBUG    Check for Read permission -> https://vulnweb-staging.firebaseio.com
scant3r     : DEBUG    Check for Write permission -> https://vulnweb-staging.firebaseio.com
scant3r     : DEBUG    Check for Read permission -> https://vulnweb-qa.firebaseio.com
scant3r     : DEBUG    Check for Write permission -> https://vulnweb-qa.firebaseio.com
scant3r     : DEBUG    Check for Read permission -> https://vulnweb-test.firebaseio.com
scant3r     : DEBUG    Check for Write permission -> https://vulnweb-test.firebaseio.com
scant3r     : DEBUG    Check for Read permission -> https://vulnwebdev.firebaseio.com
scant3r     : DEBUG    Check for Write permission -> https://vulnwebdev.firebaseio.com
scant3r     : DEBUG    Check for Read permission -> https://vulnwebstaging.firebaseio.com
scant3r     : DEBUG    Check for Write permission -> https://vulnwebstaging.firebaseio.com
scant3r     : DEBUG    Check for Read permission -> https://vulnwebtest.firebaseio.com
scant3r     : DEBUG    Check for Write permission -> https://vulnwebtest.firebaseio.com
scant3r     : DEBUG    Check for Read permission -> https://vulnwebqa.firebaseio.com
scant3r     : DEBUG    Check for Write permission -> https://vulnwebqa.firebaseio.com
scant3r     : DEBUG    TASK FINISHED: <Future at 0x7fe51a3db8d0 state=finished returned dict> | {'module': 'firebase'}
scant3r     : DEBUG    TASK FINISHED: <Future at 0x7fe51b40bdd8 state=finished returned dict> | {}
scant3r     : DEBUG    TASK FINISHED: <Future at 0x7fe51a3db5c0 state=finished returned dict> | {}
```

**Expected behavior**
some results shown 

**Screenshots**
![image](https://user-images.githubusercontent.com/9474721/173591123-f0ce765f-f5cc-435e-8705-667554c96073.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 Linux
 - Compiler [e.g. Python, PYPY]
Python
 - Version [e.g. 3.8]
 3.6.8
 - Last Commit [first line of `git log` command , EX: f8a3a9de97d1b378df21a91d34cb77df7bf7417d]
 0.9.3

**Additional context**

**Comment by knassar702** [comment]
hey @lworld0x00 , could you please provide your python version?

```bash
$ python -V
```
