### ISSUE TITLE
when install found error

### ISSUE THREAD

**Issue by rahul199300** [knassar702/scant3r#64]
when i am installing finding the error pls help. 

echo "http://testphp.vulnweb.com/listproducts.php?cat=1" | scant3r -m all 
Traceback (most recent call last):
  File "/usr/local/bin/scant3r", line 5, in <module>
    from scant3r.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/scant3r/__main__.py", line 2, in <module>
    from scant3r.core.app import Scantr
  File "/usr/local/lib/python3.10/dist-packages/scant3r/core/app.py", line 8, in <module>
    from scant3r.core.module_loader import ModuleLoader
  File "/usr/local/lib/python3.10/dist-packages/scant3r/core/module_loader.py", line 15, in <module>
    from scant3r.core.requester import httpSender
  File "/usr/local/lib/python3.10/dist-packages/scant3r/core/requester.py", line 8, in <module>
    from requests import Request, Session, packages, request
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 133, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 27, in <module>
    from . import certs
  File "/usr/lib/python3/dist-packages/requests/certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

**Comment by knassar702** [comment]
hey @rahul199300 , thanks for your report but could you please provide some information about your local ENV ?

* python version
* OS
* your installation way

**Comment by rahul199300** [comment]
- python version is - **3.10.4**
- OS- **Kali Linux**
- Installation steups-

git clone https://github.com/knassar702/scant3r.git 
Cloning into 'scant3r'...
remote: Enumerating objects: 5739, done.
remote: Counting objects: 100% (646/646), done.
remote: Compressing objects: 100% (337/337), done.
remote: Total 5739 (delta 365), reused 474 (delta 301), pack-reused 5093
Receiving objects: 100% (5739/5739), 21.26 MiB | 6.73 MiB/s, done.
Resolving deltas: 100% (3047/3047), done.

cd scant3r 
pip3 install -r requirements.txt    
Requirement already satisfied: rich==12.4.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (12.4.1)
Requirement already satisfied: requests==2.27.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.27.1)
Requirement already satisfied: colorama==0.4.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (0.4.4)
Requirement already satisfied: tldextract==3.3.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (3.3.0)
Requirement already satisfied: fuzzywuzzy==0.18.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (0.18.0)
Requirement already satisfied: pycryptodome==3.14.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (3.14.1)
Requirement already satisfied: pyyaml==6.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (6.0)
Requirement already satisfied: parsel==1.6.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 8)) (1.6.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /usr/lib/python3/dist-packages (from rich==12.4.1->-r requirements.txt (line 1)) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/lib/python3/dist-packages (from rich==12.4.1->-r requirements.txt (line 1)) (2.11.2)
Requirement already satisfied: requests-file>=1.4 in /usr/lib/python3/dist-packages (from tldextract==3.3.0->-r requirements.txt (line 4)) (1.5.1)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from tldextract==3.3.0->-r requirements.txt (line 4)) (3.3)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.10/dist-packages (from tldextract==3.3.0->-r requirements.txt (line 4)) (3.7.1)
Requirement already satisfied: six>=1.6.0 in /usr/lib/python3/dist-packages (from parsel==1.6.0->-r requirements.txt (line 8)) (1.16.0)
Requirement already satisfied: w3lib>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from parsel==1.6.0->-r requirements.txt (line 8)) (1.22.0)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from parsel==1.6.0->-r requirements.txt (line 8)) (4.8.0)
Requirement already satisfied: cssselect>=0.9 in /usr/local/lib/python3.10/dist-packages (from parsel==1.6.0->-r requirements.txt (line 8)) (1.1.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv                                   

chmod +x setup.py 

**Error find-** 

scant3r --help
Traceback (most recent call last):
  File "/usr/local/bin/scant3r", line 5, in <module>
    from scant3r.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/scant3r/__main__.py", line 2, in <module>
    from scant3r.core.app import Scantr
  File "/usr/local/lib/python3.10/dist-packages/scant3r/core/app.py", line 8, in <module>
    from scant3r.core.module_loader import ModuleLoader
  File "/usr/local/lib/python3.10/dist-packages/scant3r/core/module_loader.py", line 15, in <module>
    from scant3r.core.requester import httpSender
  File "/usr/local/lib/python3.10/dist-packages/scant3r/core/requester.py", line 8, in <module>
    from requests import Request, Session, packages, request
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 133, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 27, in <module>
    from . import certs
  File "/usr/lib/python3/dist-packages/requests/certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

**Comment by knassar702** [comment]
Could you please install it directly from git with pip in the README file


في الخميس، ٢٣ يونيو ٢٠٢٢ ٧:١٠ ص rahul199300 ***@***.***> كتب:

**Comment by rahul199300** [comment]
dear sir,
i have already done that process but found same error

**Comment by knassar702** [comment]
hey @rahul199300 , I think there's an issue with your python packages path
check this: https://stackoverflow.com/questions/67034437/no-module-named-certifi

Also you can use the Docker version 

```bash
$ docker build -t scantr .
$ echo "http://testphp.vulnweb.com/listproducts.php?cat=1" | docker run -i scant3r -m xss
```

**Comment by rahul199300** [comment]
Hey dear ,

thank you so much now its working.

**Comment by knassar702** [comment]
Nice :+1:
